### ISSUE TITLE
env and install pyriemann 

### ISSUE THREAD

**Issue by Mohammed-Baqir** [semesterprojectBCI/bci-classification#2]
Hello,
- i got this error "EnvironmentFileNotFound:" when I want to create env file using anaconda with following your code.
- and I can't find execute the installation for pyriemann  package using conda.
Thanks...

**Comment by tinorellstab** [comment]
Hi,
You should run the conda command inside the project folder.

**Comment by whj980129** [comment]
Hello, I would like to ask, if the 4 types of the 2a data set are detected, is there anything else that needs to be modified except the last fully connected layer? Because I changed to 4 categories and changed the loss function to categorical_crossentropy suitable for multiple categories, the result was not very good. I have tried many methods, but I have not been able to get good results.
